SRC@src/lib := \
	src/lib/ft_list_for_each.c \
	src/lib/ft_strchr.c \
	src/lib/ft_split.c \
	src/lib/ft_strtrim.c \
	src/lib/ft_bzero.c \
	src/lib/ft_list_insert_after.c \
	src/lib/ft_list_sort.c \
	src/lib/ft_strnstr.c \
	src/lib/ft_list_size.c \
	src/lib/ft_strmapi.c \
	src/lib/ft_list_map.c \
	src/lib/ft_isprint.c \
	src/lib/ft_atoi.c \
	src/lib/ft_list_free.c \
	src/lib/ft_strdup.c \
	src/lib/ft_list_for_each_if.c \
	src/lib/ft_list_create.c \
	src/lib/ft_tolower.c \
	src/lib/ft_list_find.c \
	src/lib/ft_toupper.c \
	src/lib/ft_list_add_front.c \
	src/lib/ft_list_swap_values.c \
	src/lib/ft_substr.c \
	src/lib/ft_memchr.c \
	src/lib/ft_putnbr_fd.c \
	src/lib/ft_strlcpy.c \
	src/lib/ft_itoa.c \
	src/lib/ft_list_sorted_insert.c \
	src/lib/ft_memset.c \
	src/lib/ft_calloc.c \
	src/lib/ft_list_merge.c \
	src/lib/ft_list_last.c \
	src/lib/ft_list_reverse_values.c \
	src/lib/ft_strlen.c \
	src/lib/ft_list_remove_if.c \
	src/lib/ft_putchar_fd.c \
	src/lib/ft_isascii.c \
	src/lib/ft_memccpy.c \
	src/lib/ft_list_add_back.c \
	src/lib/ft_strlcat.c \
	src/lib/ft_putendl_fd.c \
	src/lib/ft_memcmp.c \
	src/lib/ft_list_swap_elements.c \
	src/lib/ft_isdigit.c \
	src/lib/ft_strrchr.c \
	src/lib/ft_list_sorted_merge.c \
	src/lib/ft_putstr_fd.c \
	src/lib/ft_list_reverse.c \
	src/lib/ft_isalpha.c \
	src/lib/ft_list_clear.c \
	src/lib/ft_strncmp.c \
	src/lib/ft_isalnum.c \
	src/lib/ft_memcpy.c \
	src/lib/ft_memmove.c \
	src/lib/ft_strjoin.c \
	src/lib/ft_list_at.c \
	src/lib/ft_list_from.c \

SRC@src/philo := \
	src/philo/main.c \

SRC@src/philo_bonus := \
	src/philo_bonus/main.c \
